In [2]:
import numpy as np
import random
from sklearn import datasets
import pandas as pd
import copy

$Implementation$

In [3]:
def initialize_weight_matrix(x):
    w = []
    for i in range(1,len(x)):
        w.append(np.random.randn(len(x[i-1]),len(x[i])))
    return w

In [4]:
def feed_forward(w, x, y):
    # Feed Forward
    for i in range(1,len(x)):
        x[i] = np.matmul(w[i-1].T, y[i-1].T)
        y[i] = 1/(1+np.e**(-x[i]))

In [5]:
def backpropagate(w, x, y, d_out):
    # Backpropagation
    # Initial setup
    w_inter = []
    for i in range(1,len(x)):
        w_inter.append(np.random.randn(len(x[i-1]),len(x[i])))

    # Layer - 1
    for i in range(w[1].shape[0]):
        for j in range(w[1].shape[1]):
            w_inter[1][i][j] = w[1][i][j] - 0.001*(y[2][j]-d_out[j])*(y[2][j]*(1-y[2][j]))*y[1][i]

    # Layer - 2
    for h in range(w[0].shape[0]):
        for i in range(w[0].shape[1]):
            w_inter[0][h][i] = w[0][h][i] - 0.001*((y[2][0]-d_out[0])*(y[2][0]*(1-y[2][0]))*(w[1][i][0])*(y[1][i]*(1-y[1][i]))*(y[0][h]) +
                                            (y[2][1]-d_out[1])*(y[2][1]*(1-y[2][1]))*(w[1][i][1])*(y[1][i]*(1-y[1][i]))*(y[0][h]))

    return w_inter

In [14]:
def calculate_error(y_out, d_out):
    e = 0
    for i,j in list(zip(y_out, d_out)):
        e+=(i-j)**2
    return e/2

def diff_first_principles(e2, e1, w2, w1):
    return (e2-e1)/(w2-w1)

def backpropagate_newton_raphson(w, x, y, d_out):
    # Backpropagation
    # Initial setup
    w_inter = copy.deepcopy(w)
    x_temp = copy.deepcopy(x)
    y_temp = copy.deepcopy(y)

    # Generic backpropagate
    err1 = calculate_error(y[-1], d_out)
    const1 = 6
    for k in range(len(w)):
        for i in range(w[k].shape[0]):
            for j in range(w[k].shape[1]):
                w1 = w[k][i][j]
                w[k][i][j]+=const1*(10**-3)
                w2 = w[k][i][j]
                feed_forward(w, x_temp, y_temp)
                w[k][i][j]-=const1*(10**-3)
                err2 = calculate_error(y_temp[-1], d_out)
                diff = diff_first_principles(err2, err1, w2, w1)
                w_inter[k][i][j] = w[k][i][j] - 0.01*diff

    return w_inter

In [15]:
iris = datasets.load_iris()
iris['data'][:5,:3]

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4]])

In [16]:
x = [np.zeros(3), np.zeros(4), np.zeros(2)]
w = initialize_weight_matrix(x)
for runs in range(600):
    for inp,out in list(zip(iris['data'][:100,:3],iris['target'][:100])):
        x = [np.array(inp), np.zeros(4), np.array(2)]                   # Inputs to neurons
        '''
        # To add new layer
        x.append(np.zeros(n))
        '''
        y = [np.array(inp), np.zeros(4), np.zeros(2)]                   # Output from neurons
        '''
        # To add new layer
        y.append(np.zeros(n))
        '''
        feed_forward(w,x,y)
        d_out = [1,0] if out==0 else [0,1]
        w = backpropagate_newton_raphson(w,x,y,d_out)



In [17]:
w

[array([[ 2.74014155,  0.48182297,  0.85159042, -2.37548682],
        [-0.11244756,  0.68265062,  1.47539148, -0.02783873],
        [-0.5577782 ,  1.48909804, -3.39481363, -0.99777046]]),
 array([[-1.26110064,  2.64315334],
        [-1.3268846 , -0.0530288 ],
        [ 5.32290618, -5.34083099],
        [ 0.07530041,  0.24649119]])]

In [21]:
x_pred = [np.array(iris['data'][33,:3]),np.zeros(4),np.zeros(2)]
y_pred = x_pred
feed_forward(w,x_pred,y_pred)
y_pred[2]

array([0.93842789, 0.06070772])

$Verification$

In [36]:
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [37]:
df = pd.DataFrame(data=iris['data'], columns=iris['feature_names'])
df['classes'] = iris['target']
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   classes  
0        0  
1        0  
2        0  
3        0  
4        0

In [38]:
df.shape

(150, 5)

In [39]:
df.drop('petal width (cm)',axis=1,inplace=True)
df = df[(df['classes'] == 0) | (df['classes'] == 1)]
df.shape,df.head()

((100, 4),
    sepal length (cm)  sepal width (cm)  petal length (cm)  classes
 0                5.1               3.5                1.4        0
 1                4.9               3.0                1.4        0
 2                4.7               3.2                1.3        0
 3                4.6               3.1                1.5        0
 4                5.0               3.6                1.4        0)

In [40]:
from sklearn.neural_network import MLPClassifier
ver_model = MLPClassifier(hidden_layer_sizes=(4,),solver='sgd', max_iter=600)

In [41]:
ver_model.fit(df.drop('classes',axis=1),y=df['classes'])

C:\Users\kishl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (600) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(4,), max_iter=600, solver='sgd')

In [42]:
ver_model.coefs_

[array([[-0.20171404, -0.60254268, -0.00456867,  0.00722509],
        [-0.22525707, -0.50083807,  1.10702285, -0.91763517],
        [-0.32801113, -0.2217566 , -0.83534515,  0.06212787]]),
 array([[-0.38020621],
        [-0.51037681],
        [-1.47339927],
        [-0.12702933]])]

In [43]:
ver_model.predict_proba([list(df.iloc[13,:3])])

C:\Users\kishl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(


array([[0.94580611, 0.05419389]])